@startuml

interface LoggerInterface << Component >> {
    +log()
}

class Logger << ConcreteComponent >> {
    -message : string
	+__construct(message : string)
    +log()
}

class LoggerDecorator << Decorator >> {
    #decoratedLogger : LoggerInterface
	+__construct(message : LoggerInterface)
    +log()
}

class LoggerWithDateDecorator << ConcreteDecorator >> {
    -datetime : DateTime
	+__construct(message : LoggerInterface, datetime : DateTime)
    +log()
}

class LoggerWithErrorLevelDecorator << ConcreteDecorator >> {
    +{static}ERROR = "#ff0000"
    +{static}INFO = "#0000ff"
    +{static}WARNING = "#ffbb00"
    -errorLevel : string
	+__construct(message : LoggerInterface, errorLevel : string = "#0000ff")
    +log()
}

class Logger implements LoggerInterface
class LoggerDecorator implements LoggerInterface
class LoggerWithDateDecorator extends LoggerDecorator
class LoggerWithErrorLevelDecorator extends LoggerDecorator

right footer © Vlad Riabchenko <contact@vria.eu>

@enduml
